### ISSUE TITLE
nanmaximum and nanminimum yield NaN when too many NaN's are present in Array

### ISSUE THREAD

**Issue by astrobc1** [brenhinkeller/NaNStatistics.jl#19]
Steps to reproduce:

`x=[1.:100;]`
`x[90:end] .= NaN`
`using NaNStatistics`
`@show nanmaximum(x)`

Results in:

`nanmaximum(x) = 89`

(which is correct)

`x=[1.:100;]`
`x[50:end] .= NaN`
`using NaNStatistics`
`@show nanmaximum(x)`

Results in:

`nanmaximum(x) = NaN`

(which is wrong)

The magic cutoff is 66. No clue why.

----

NaNStatistics v0.6.6

**Comment by brenhinkeller** [comment]
Hmm, can reproduce. This seems (AFAIU) to have been caused by a change in VectorizationBase that broke the assumptions I made about what to dispatch on in the `nanmin` and `nanmax` functions that get `vreduce`d. Should have a fix shortly.

**Comment by brenhinkeller** [comment]
Should be fixed now in v0.6.10, but I'll leave open until you can confirm.

https://github.com/JuliaRegistries/General/pull/58246

**Comment by astrobc1** [comment]
Tests for my use cases are now working as expected. Thanks for the quick fix! Closed.

**Comment by brenhinkeller** [comment]
Awesome! Thanks for the report!
