### ISSUE TITLE
nancumsum

### ISSUE THREAD

**Issue by florian-st** [brenhinkeller/NaNStatistics.jl#25]
Hi, first of all thanks for this awesome package! Would you consider adding a function nancumsum, to calculate the cumulative sum ignoring NaN?

**Comment by brenhinkeller** [comment]
Sure, we could do that

**Comment by brenhinkeller** [comment]
#26 should do it -- won't be quite as fast as `nansum` because we can't use `@turbo`, but we can use the same `@generated`  function approach as the other stats to cover all the possible dimensional cases

**Comment by brenhinkeller** [comment]
You can try this version https://github.com/brenhinkeller/NaNStatistics.jl/releases/tag/v0.6.14
