### ISSUE TITLE
nancor > 1

### ISSUE THREAD

**Issue by cossio** [brenhinkeller/NaNStatistics.jl#32]
```
nancor([NaN, .01, 2.3, .4], [0.1, NaN, 3.2, 1.2])
# 1.311520448621402
```

The Pearson correlation should be `< 1`.

**Comment by brenhinkeller** [comment]
Thanks, think I found the source of this

**Comment by brenhinkeller** [comment]
https://github.com/JuliaRegistries/General/pull/76545 should have the fix, once that gets merged

**Comment by cossio** [comment]
Thanks!
