### ISSUE TITLE
Replacing LoopVectorization

### ISSUE THREAD

**Issue by JamesWrigley** [brenhinkeller/NaNStatistics.jl#47]
Hi there,
What with LoopVectorization.jl getting deprecated in Julia v1.11, are there any plans to replace it in this package? From what I've read the only path forward (while keeping performance) is to write efficient kernels ourselves.

**Comment by brenhinkeller** [comment]
It’s not clear that there’s any replacement forthcoming anywhere in the community. If there is we can try to port the implementations in this package to that, but currently the next best thing is ***@***.*** @fastmath`, which is what LoopVectoriztation falls back to anyways (so things should keep working here, and will still benefit for the ***@***.***` functions for each dimensional case, just probably not quite as fast as they used to be)

**Comment by JamesWrigley** [comment]
I see, what do you think about explicitly replacing `@turbo` with `@fastmath` just to remove the dependency? (I might be able to find time for it if you think that's a good idea)

**Comment by brenhinkeller** [comment]
Eventually probably yes if no one resurrects LoopVectorization, but no rush I think

**Comment by brenhinkeller** [comment]
While it looks like we can't use `@fastmath` due to what that does to handling of `NaN`s, `@simd ivdep for` seems to work pretty well here

Closed by #48
