### ISSUE TITLE
Update deps + re-enable compat helper

### ISSUE THREAD

**Issue by briochemc** [brenhinkeller/NaNStatistics.jl#49]
It looks like compat helper has been disabled and now the deps are a bit behind. For example I'd like to use Static v1. @brenhinkeller Could you re-enable compat helper and run it?

**Comment by brenhinkeller** [comment]
Do you know how to re-enable that? There's some annoying github setting that deactivates automatically it after some time

**Comment by briochemc** [comment]
I think you just click on actions -> Compat Helper, and then as the owner you should have a button to reactivate it. Yes I have the same issues with a few packages of mine.

**Comment by brenhinkeller** [comment]
Oh cool, thanks!

**Comment by briochemc** [comment]
Can you tag a new release with 40d8df7?

**Comment by brenhinkeller** [comment]
Oh sure

**Comment by briochemc** [comment]
Thanks!
